export const AUTH_SIGNIN = 'AUTH/SIGNIN'
export const AUTH_LOGOUT = 'AUTH/LOGOUT'

export const USER_INFO = 'USER/INFO'

export const EXCERCISE_GETALL = 'EXCERCISE/GETALL'

export const JOURNAL_ADD = 'JOURNAL/ADD'
export const JOURNAL_REMOVE = 'JOURNAL/REMOVE'
export const JOURNAL_CLEARPLAN = 'JOURNAL/CLEARPLAN'
export const JOURNAL_CLEARDAILYPLAN = 'JOURNAL/CLEARDAILYPLAN'
export const JOURNAL_ADDTODAYLY = 'JOURNAL/ADDTODAYLY'
export const JOURNAL_ADDCOUNTER = 'JOURNAL/ADDCOUNTER'
